### ISSUE TITLE
Crashing when deploying CSI driver

### ISSUE THREAD

**Issue by delassiter** [janosmiko/hetzner-k3s#4]
In a new and empty hcloud project I created a token and used the docker image and the example yaml-file (see below). Only change is the k3s version, for which I chose 1.25.5-k3s1. All resources are created as expected, but when hetzner-k3s reaches the "Deploying Hetzner CSI Driver..." step the application crashes:

```
Command output: Error from server (NotFound): error when deleting "STDIN": csidrivers.storage.k8s.io "csi.hetzner.cloud" not found
Exit code: exit status 1
Error: cannot create cluster: cannot deploy hetzner csi driver: shell command exited with error: 1, output: Error from server (NotFound): error when deleting "STDIN": csidrivers.storage.k8s.io "csi.hetzner.cloud" not found
```

Restarting the cluster-create command does not yield a different result.

In this line https://github.com/janosmiko/hetzner-k3s/blob/13e7b155da02a9ecfcdc59d06ba638bf34d65607/internal/k3s/hetzner.go#L115 the CSIDriver is deleted from the cluster, without existing. This causes kubectl to return non-zero and the error check in line 118 to fail. I understand the need for preemptively removing the CSIDriver, since it's immutable, but  when creating a new cluster this CSIDriver is never available and can't be removed.

I've manually added the CSIDriver with the yaml configuration (as defined for deletion) https://github.com/janosmiko/hetzner-k3s/blob/13e7b155da02a9ecfcdc59d06ba638bf34d65607/internal/k3s/hetzner.go#L307-L316 and then ran the `create-cluster` command again. This time all ran successfully.

I'm happy to provide more information if requried.

As mentioned above my yaml-file:

```yml
---
hetzner_token: <my-token>
cluster_name: test
kubeconfig_path: "/cluster/kubeconfig"
k3s_version: v1.25.5+k3s1
public_ssh_key_path: "/tmp/.ssh/id_rsa.pub"
private_ssh_key_path: "/tmp/.ssh/id_rsa"
verify_host_key: false
location: nbg1
schedule_workloads_on_masters: false
masters:
  instance_type: cpx21
  instance_count: 3
worker_node_pools:
  - name: small
    instance_type: cpx21
    instance_count: 4
  - name: big
    instance_type: cpx31
    instance_count: 2
autoscaling_node_pools:
  - name: small
    instance_type: cx41
    instance_min: 3
    instance_max: 5
  - name: big
    instance_type: cpx51
    instance_max: 10
post_create_commands:
  - apt update
  - apt upgrade -y
  - apt autoremove -y
  - shutdown -r now
enable_encryption: true

```
Command to run:
```
docker run --rm -it \
  -v ${PWD}:/cluster \
  -v ${HOME}/.ssh:/tmp/.ssh \
  janosmiko/hetzner-k3s:v0.1.5 \
  create-cluster \
  --config-file /cluster/test.yaml
```
