### ISSUE TITLE
Make hetzner_token optional

### ISSUE THREAD

**Issue by jonasbadstuebner** [janosmiko/hetzner-k3s#6]
If you can use the env variable (which did not work for me btw), the hetzner_token key should not be required in the yaml.

**Comment by janosmiko** [comment]
How do you try to pass an environment variable?

I tried setting the `hetzner_token` to be empty in my config:
```yaml
---
hetzner_token: ""
cluster_name: truncated
kubeconfig_path: "/cluster/kubeconfig"
k3s_version: v1.24.6+k3s1
public_ssh_key_path: "~/.ssh/id_rsa.pub"
private_ssh_key_path: "~/.ssh/id_rsa"
verify_host_key: false
...
```

On the first run it fails as expected:

```shell
docker run --rm -it -v "${PWD}":/cluster -v "${PWD}/../keys-dev":/tmp/.ssh "janosmiko/hetzner-k3s:v0.1.6" create-cluster --config-file /cluster/config.yaml
invalid configuration: validation failed: Key: 'Config.HetznerToken' Error:Field validation for 'HetznerToken' failed on the 'required' tag
```

But when I pass a token using an environment variable it works again:
```           
hetzner-k3s/dev-rc-mgmt [main●] » docker run --rm -e HETZNER_TOKEN=asdqwe -it -v "${PWD}":/cluster -v "${PWD}/../keys-dev":/tmp/.ssh "janosmiko/hetzner-k3s:v0.1.6" create-cluster --config-file /cluster/config.yaml
2023-01-05T10:11:33Z    INFO    Creating cluster...
Enter SSH Passhphrase: 

```
